<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>QuanLyNhanVien</RootNamespace>
    <!-- Đảm bảo output tiếng Việt hiển thị đúng trên Console Windows -->
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

</Project>
